### ISSUE TITLE
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://localhost:8080/v1/models'

### ISSUE THREAD

**Issue by fahdmirza** [leoguillaume/VLLMEmbeddings#2]
Hi,
 I have installed this on Ubuntu 22.04 in conda environment. All the docker containers are UP and I used .env.example file in the repo, but getting following error:

> 
(albertmodels) Ubuntu@0136-ict-prxmx50056:~/albert-models$ python tests.py --debug
2024-07-12 01:47:35,349:INFO: test: http://localhost:8080/v1/models
2024-07-12 01:47:35,350:DEBUG: Request options: {'method': 'get', 'url': '/models', 'post_parser': <function SyncAPIClient._request_api_list.<locals>._parser at 0x7d326f128a40>, 'json_data': None}
2024-07-12 01:47:35,355:DEBUG: Sending HTTP Request: GET http://localhost:8080/v1/models
2024-07-12 01:47:35,355:DEBUG: connect_tcp.started host='localhost' port=8080 local_address=None timeout=5.0 socket_options=None
2024-07-12 01:47:35,356:DEBUG: connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7d326ed9a990>
2024-07-12 01:47:35,357:DEBUG: send_request_headers.started request=<Request [b'GET']>
2024-07-12 01:47:35,357:DEBUG: send_request_headers.complete
2024-07-12 01:47:35,357:DEBUG: send_request_body.started request=<Request [b'GET']>
2024-07-12 01:47:35,357:DEBUG: send_request_body.complete
2024-07-12 01:47:35,357:DEBUG: receive_response_headers.started request=<Request [b'GET']>
2024-07-12 01:47:35,368:DEBUG: receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'Server', b'nginx/1.27.0'), (b'Date', b'Fri, 12 Jul 2024 01:47:35 GMT'), (b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'21'), (b'Connection', b'keep-alive')])
2024-07-12 01:47:35,368:INFO: HTTP Request: GET http://localhost:8080/v1/models "HTTP/1.1 500 Internal Server Error"

> 

Thanks.

**Comment by leoguillaume** [comment]
Hi, 

I think it could come from the .env.example file. You need to comment out the API key variable or comment out the relative lines for the different containers in the docker compose. 
If you're passing an API key, add to the command for testing: python tests.py --api-key=<key>

I'll update the repo !

Another way : 
The model maybe downloaded the first time you launch the containers, you need to wait a few minutes (and check that the vllm and tei containers are up with docker logs -f --tail 100 {container}).

**Comment by fahdmirza** [comment]
``Thanks for the help.

Yes I waited for more than10 minutes. Tried it again with your new test command now I get following error:
`(albertmodels) Ubuntu@0136-ict-prxmx50056:~/albert-models$ python tests.py --base-url http://localhost:8080 --api-key mysecretkey --debug
2024-07-12 08:10:32,027:INFO: test: http://localhost:8080/models
2024-07-12 08:10:32,029:DEBUG: Request options: {'method': 'get', 'url': '/models', 'post_parser': <function SyncAPIClient._request_api_list.<locals>._parser at 0x7528e314ca40>, 'json_data': None}
2024-07-12 08:10:32,034:DEBUG: Sending HTTP Request: GET http://localhost:8080/models
2024-07-12 08:10:32,034:DEBUG: connect_tcp.started host='localhost' port=8080 local_address=None timeout=5.0 socket_options=None
2024-07-12 08:10:32,036:DEBUG: connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7528e2fb2a90>
2024-07-12 08:10:32,036:DEBUG: send_request_headers.started request=<Request [b'GET']>
2024-07-12 08:10:32,036:DEBUG: send_request_headers.complete
2024-07-12 08:10:32,036:DEBUG: send_request_body.started request=<Request [b'GET']>
2024-07-12 08:10:32,036:DEBUG: send_request_body.complete
2024-07-12 08:10:32,036:DEBUG: receive_response_headers.started request=<Request [b'GET']>
2024-07-12 08:10:32,037:DEBUG: receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Server', b'nginx/1.27.0'), (b'Date', b'Fri, 12 Jul 2024 08:10:32 GMT'), (b'Content-Type', b'text/html'), (b'Content-Length', b'153'), (b'Connection', b'keep-alive')])
2024-07-12 08:10:32,037:INFO: HTTP Request: GET http://localhost:8080/models "HTTP/1.1 404 Not Found"
2024-07-12 08:10:32,037:DEBUG: receive_response_body.started request=<Request [b'GET']>
2024-07-12 08:10:32,037:DEBUG: receive_response_body.complete
2024-07-12 08:10:32,038:DEBUG: response_closed.started
2024-07-12 08:10:32,038:DEBUG: response_closed.complete
2024-07-12 08:10:32,038:DEBUG: HTTP Response: GET http://localhost:8080/models "404 Not Found" Headers({'server': 'nginx/1.27.0', 'date': 'Fri, 12 Jul 2024 08:10:32 GMT', 'content-type': 'text/html', 'content-length': '153', 'connection': 'keep-alive'})
2024-07-12 08:10:32,038:DEBUG: request_id: None
2024-07-12 08:10:32,038:DEBUG: Encountered httpx.HTTPStatusError
Traceback (most recent call last):
  File "/home/Ubuntu/miniconda3/envs/albertmodels/lib/python3.11/site-packages/openai/_base_client.py", line 1025, in _request
    response.raise_for_status()
  File "/home/Ubuntu/miniconda3/envs/albertmodels/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'http://localhost:8080/models'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
2024-07-12 08:10:32,039:DEBUG: Not retrying
2024-07-12 08:10:32,039:DEBUG: Re-raising status error
2024-07-12 08:10:32,039:ERROR: Failed to test http://localhost:8080/models: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.27.0</center>
</body>
</html>
2024-07-12 08:10:32,039:ERROR: name 'response' is not defined
2024-07-12 08:10:32,039:ERROR: name 'model_id' is not defined
2024-07-12 08:10:32,039:ERROR: name 'model_id' is not defined
2024-07-12 08:10:32,039:ERROR: name 'model_id' is not defined
2024-07-12 08:10:32,039:ERROR: name 'model_id' is not defined
2024-07-12 08:10:32,039:ERROR: name 'model_id' is not defined
2024-07-12 08:10:32,067:DEBUG: close.started
2024-07-12 08:10:32,067:DEBUG: close.complete
(albertmodels) Ubuntu@0136-ict-prxmx50056:~/albert-models$ docker ps
CONTAINER ID   IMAGE                                                  COMMAND                  CREATED         STATUS         PORTS                                               NAMES
8b8b866d8090   vllm/vllm-openai:latest                                "python3 -m vllm.ent…"   5 minutes ago   Up 5 minutes   8000/tcp                                            serve-vllm-1
cf1445452225   ghcr.io/etalab-ia/albert-models/fastapi:latest         "uvicorn main:app --…"   5 minutes ago   Up 5 minutes   8000/tcp                                            serve-fastapi-1
9d21a42a33d0   ghcr.io/etalab-ia/albert-models/nginx:latest           "/docker-entrypoint.…"   5 minutes ago   Up 5 minutes   80/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   serve-nginx-1
534520ab5035   ghcr.io/huggingface/text-embeddings-inference:latest   "text-embeddings-rou…"   5 minutes ago   Up 5 minutes   80/tcp                                              serve-tei-1
(albertmodels) Ubuntu@0136-ict-prxmx50056:~/albert-models$
`

**Comment by fahdmirza** [comment]
Hi,
 I cleaned up everything , and tried again including re-cloning your repo and got following error:

(albertmodels) Ubuntu@0136-ict-prxmx50056:~/albert-models$ docker compose --env-file .env.example up --detach
WARN[0000] /home/Ubuntu/albert-models/docker-compose.yml: `version` is obsolete
service "vllm" refers to undefined volume "./models"/TheBloke/OpenHermes-2.5-Mistral-7B-GPTQ: invalid compose project
(albertmodels) Ubuntu@0136-ict-prxmx50056:~/albert-models$
`
